import React, { useState } from 'react';
import { Icon, type IconName } from '../components/Icons';
import { Button } from '../components/Button';
import { Logo } from '../components/Logo';

export const Reports: React.FC = () => {
  const [selectedProject, setSelectedProject] = useState('Chennai Site Survey');
  const [selectedSections, setSelectedSections] = useState<string[]>([
    'Executive summary',
    'Feature measurements',
    'CRS & processing metadata',
  ]);

  const reportActions: [string, string, IconName][] = [
    ['Generate Site Report', 'Full measurement summary', 'report'],
    ['Export CSV', 'Structured feature data', 'download'],
    ['Export JSON', 'API-ready geometry data', 'code'],
    ['Download PDF', 'Branded field report', 'file'],
  ];

  const sectionsList = [
    'Executive summary',
    'Feature measurements',
    'CRS & processing metadata',
    'Geometry exceptions',
  ];

  const toggleSection = (s: string) => {
    if (selectedSections.includes(s)) {
      setSelectedSections(selectedSections.filter((item) => item !== s));
    } else {
      setSelectedSections([...selectedSections, s]);
    }
  };

  return (
    <div className="page">
      <section className="hero-row compact">
        <div>
          <div className="eyebrow">DOCUMENTATION</div>
          <div className="page-title">Measurement Reports</div>
          <p>Generate audit-ready summaries for teams and stakeholders.</p>
        </div>
        <Button icon="plus" onClick={() => window.print()}>
          Generate report
        </Button>
      </section>

      <div className="report-layout">
        <div>
          <div className="report-actions">
            {reportActions.map(([title, desc, iconName]) => (
              <div
                className="report-action panel"
                key={title}
                onClick={() => alert(`Starting ${title}...`)}
              >
                <span>
                  <Icon name={iconName} />
                </span>
                <div>
                  <strong>{title}</strong>
                  <small>{desc}</small>
                </div>
                <Icon name="arrow" />
              </div>
            ))}
          </div>

          <div className="panel report-options">
            <div className="panel-title">Report configuration</div>
            <label>
              Project
              <select
                value={selectedProject}
                onChange={(e) => setSelectedProject(e.target.value)}
              >
                <option value="Chennai Site Survey">Chennai Site Survey</option>
                <option value="NH Infrastructure Corridor">NH Infrastructure Corridor</option>
                <option value="Eastern Corridor Railway">Eastern Corridor Railway</option>
              </select>
            </label>
            <label>Include sections</label>
            {sectionsList.map((x) => {
              const isChecked = selectedSections.includes(x);
              return (
                <div
                  className="checkbox-row"
                  key={x}
                  onClick={() => toggleSection(x)}
                  style={{ cursor: 'pointer' }}
                >
                  <span style={{ opacity: isChecked ? 1 : 0.2 }}>
                    <Icon name="check" size={12} />
                  </span>
                  {x}
                </div>
              );
            })}
          </div>
        </div>

        <div className="report-preview-wrap">
          <div className="preview-label">
            <span>REPORT PREVIEW</span>
            <span>Page 1 of 4</span>
          </div>
          <div className="report-paper">
            <div className="report-brand">
              <Logo compact />
              <div>
                <span>GENERATED BY</span>
                <strong>TERRAFLOW</strong>
              </div>
            </div>
            <div className="report-kicker">SITE MEASUREMENT REPORT</div>
            <div className="report-title">
              Chennai
              <br />
              Site Survey
            </div>
            <div className="report-rule" />
            <div className="report-meta">
              <div>
                <span>PROJECT</span>
                <strong>Chennai Metro Site</strong>
              </div>
              <div>
                <span>PROCESSING DATE</span>
                <strong>07 Oct 2026</strong>
              </div>
            </div>
            <div className="report-total">
              <span>TOTAL MEASURED AREA</span>
              <strong>
                48,293.72 <i>m²</i>
              </strong>
            </div>
            <div className="report-data">
              <div>
                <span>TOTAL FEATURES</span>
                <strong>1,284</strong>
              </div>
              <div>
                <span>TOTAL LINE LENGTH</span>
                <strong>128.43 km</strong>
              </div>
              <div>
                <span>SOURCE CRS</span>
                <code>EPSG:4326</code>
              </div>
              <div>
                <span>MEASUREMENT CRS</span>
                <code>EPSG:32644</code>
              </div>
            </div>
            <div className="report-footer">
              Verified geospatial processing record{' '}
              <span>TERRAFLOW / TF-2026-10284</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Reports;
